name: Bug Report
description: Report an issue or unexpected behavior
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this bug. Your suggestions help me to improve the project.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the issue
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can this issue be reproduced?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: Describe what actually happens...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to illustrate the issue
      placeholder: Drag and drop your images here

  - type: dropdown
    id: device
    attributes:
      label: Device
      description: On what type of device does this issue occur?
      options:
        - Desktop
        - Mobile
        - Tablet
        - Other
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Other
    validations:
      required: true

  - type: input
    id: browser_version
    attributes:
      label: Browser Version
      description: Which version of the browser are you using?
      placeholder: e.g. 120.0.6099.109

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - iOS
        - Android
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other relevant information about the issue
      placeholder: Additional context...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Before submitting, please verify the following
      options:
        - label: I have checked that no similar issue already exists
          required: true
        - label: I have tested with the latest version of the project
          required: true
        - label: The issue is reproducible
          required: true